### PR TITLE
Don't let the blank identifier get marked as unused

### LINKED ISSUE #6: Deadcode should not detect "_ is unused"
It's common in go to validate a type satisifies an interface with something like ```var _ io.Writer = &MyWriter{}```, however deadcode detects this.  Deadcode should not message on ```_``` assigned global variables.

### PR DESCRIPTION
**Pull request by reillywatson**
Fixes #6.

### CODE REVIEW

**Comment by cep21** [comment]
:+1:

**Comment by tsuna** [comment]
can we get this merged?

**Comment by tsuna** [comment]
@remyoudompheng ping

**Comment by tsuna** [comment]
ping

**Comment by tsuna** [comment]
Thanks :)

**Pull request merged**
